# sonar-project.properties 
sonar.projectKey=vumaihayquatroi_8.2C-Task2 
sonar.organization=vumaihayquatroi 
sonar.host.url=https://sonarcloud.io 
sonar.login=${SONAR_TOKEN} 
sonar.sources=. 
sonar.exclusions=node_modules/**,test/** 
sonar.javascript.lcov.reportPaths=coverage/lcov.info 
sonar.projectName=NodeJS Goof Vulnerable App 
sonar.sourceEncoding=UTF-8 
